// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_project_region: 'eu-west-1',
  // Cognito
  aws_cognito_identity_pool_id:
    'eu-west-1:10c38049-b189-4cdf-9017-636590e18284',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_nvd43ap7e',
  aws_user_pools_web_client_id: '5pe9mliasj9t3v9pus680ujtaa',
  aws_mandatory_sign_in: false,
  // Amazon S3 bucket
  aws_user_files_s3_bucket: 'dealimited-test.images.eu-west-3',
  aws_user_files_s3_bucket_region: 'eu-west-3',
  // AppSync
  aws_appsync_graphqlEndpoint:
    'https://5vg2k6a7qzglzns3d5hkcguhnm.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'AWS_IAM'
};

export default awsmobile;
